name: Check GitHub Users

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/check-github-users.yml'
      - 'data.json'

jobs:
  check-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Filter valid GitHub users
        run: |
          set -e
          tmpfile=$(mktemp)
          > $tmpfile
          for item in $(jq -c '.[]' data.json); do
            username=$(echo "$item" | jq -r '.[0]')
            echo "Checking user: $username"
            if curl -s -o /dev/null -w "%{http_code}" "https://github.com/${username}" | grep -q "^2"; then
              echo "User $username exists"
              echo "$item" >> $tmpfile
            else
              echo "User $username does not exist"
            fi
          done
          # 合并所有有效项为 JSON 数组
          jq -s '.' $tmpfile > data.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 筛选有效 GitHub 用户
          file_pattern: data.json