name: Check GitHub Users

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/check-github-users.yml'
      - 'data.json'

jobs:
  check-users:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Filter valid GitHub users
        run: |
          #!/usr/bin/env bash
          set -e

          # 读取 data.json 并处理
          jq -c '.[]' data.json | while read -r item; do
            username=$(echo "$item" | jq -r '.[0]')
            # 检查 GitHub 用户页面是否存在
            if curl -s -o /dev/null -w "%{http_code}" "https://github.com/${username}" | grep -q "^2"; then
              echo "$item"
            fi
          done | jq -s '.' > data.filtered.json
          mv data.filtered.json data.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 筛选有效 GitHub 用户
          file_pattern: data.json