name: lscpu

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  concurrent-jobs:
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    # strategy:
    #   max-parallel: 20
    #   matrix:
    #     job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    steps:
      - name: 记录时间戳
        shell: bash
        run: |
          lscpu  
