name: MySQL Image Retag and Push

on:
  workflow_dispatch:
    inputs:
      force:
        description: '是否强制推送'
        required: false
        type: boolean
        default: false

jobs:
  retag-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: paulojsmedeiros
      DOCKER_PASSWORD: YPH8DeGGVkFkFXmf91z88FcyoKs
    steps:
      - uses: ./.github/actions/mysql-retag
        with:
          force: ${{ inputs.force }}
